### ISSUE TITLE
mi_ksg_core - fractionate_data()

### ISSUE THREAD

**Issue by neuRowsATL** [neuRowsATL/ContinuousMIEstimation#23]
`r = fractionate_data(obj, k)`

    This function segments the data into data fraction groups. 

    We iterate through each number of subsamples to make. First, we randomly permute the indices of x so that the subgroups of data are randomly selected. Then we segment the data into relatively equal sized subgroups. Next a while loop assigns a random hexadecimal key to the subsampled estimates. 

    **Note:** There may be something wrong with this while loop. We should check to see if the `strcmp(...)` is working the way we think it is. Some subsamples got eroneously clumped together in some of my runs of this script. 

    Next, the data is split into each subsampled group and filled into a cell array. 

    These functions look good, and should be working similarly. 

    **Note:** We should check to verify that the subsampled groups consist of what we think they consist of at this level.

**Comment by bark-rach** [comment]
Just add a check that the fractionated data consists of what we think it does at this level.

**Comment by neuRowsATL** [comment]
neurowsatl still has not implemented the update loop that is supposed to make sure that there are enough elements in the arrays with unique keys/indices. thx

**Comment by bark-rach** [comment]
THis has been resolved!
