### ISSUE TITLE
mi_analysis - reparameterize

### ISSUE THREAD

**Issue by neuRowsATL** [neuRowsATL/ContinuousMIEstimation#28]
I would like to change the way that the data reparameterizes the distribution by shuffling the indices. But the problem is that we may be concerned about non-stationarities. In my code, the data is reparameterized in each dimension independently, and each subgroup is reparameterized separately. So within each sub-group, a Gaussian distribution is made.

Note: I think this is also something that should be discussed. Does it make sense to reparameterize the data to generate a Gaussian distribution within each subgroup. This is one of the challenges of having data that varies in its dimensionality.

**Comment by neuRowsATL** [comment]
This needs to be rewritten as its own stand-alone function -- which it is already. The function needs to be updated to take into consideration details noted above.

**Comment by bark-rach** [comment]
We will reparameterize all continuous variables. This should probably be done in mi_analysis now.
