### ISSUE TITLE
mi_ksg_core - get_mi(), automate k

### ISSUE THREAD

**Issue by neuRowsATL** [neuRowsATL/ContinuousMIEstimation#35]
Update return values:

`threshold = -1`: Return "raw" mutual information and error
`threshold = 0`: Return MI > 0 (0 otherwise) and return error regardless of magnitude
`threshold > 0`: Return MI > 0 (0 otherwise) and check that MI is above MI error threshold

**Comment by bark-rach** [comment]
Add an optional input- k-value. 
Make a new function: `get_k`:  Find k values that have consistent MI estimates across at least four data fractions (though more is preferable --> we'll probably have to use weighting coefficients for different factors or something?). Checks that errors for all those estimates are below a certain magnitude (2-3 sds?). If plots do not meet these criteria, eliminate them from the list of kosher k-values. Compare errors across remaining k values. Remove errors that are much larger than others. Compare the estimate from the remaining k-values. If they agree, average them. If not, then make a note. 

*I'm not sure if this function should go here, or if this function should go in the analysis object. Perhaps if we put it in the analysis object, then we can have the k-dependence plots only saved if they need to be audited by the user?*

**Comment by neuRowsATL** [comment]
Will need to discuss how to keep information about what k-values we've run, while maintaining info about which k-values to use.

**Comment by neuRowsATL** [comment]
** Use opt_k and k_values to store info

**Comment by neuRowsATL** [comment]
Need to lookup how to average std/error values.... there should be a table somewhere in the aether...
